#!/bin/bash

if [ -z "$1" ]; then
	echo "USAGE: $(basename $0) [PACKAGE_NAME]";
	exit 1;
fi

NAME=$1
OS_RELEASE=$(lsb_release -rs | cut -f1 -d.)

if [ -e SPECS/${NAME}-${OS_RELEASE}.spec ]; then
	echo "SPECS/${NAME}-${OS_RELEASE}.spec";
	exit 0;
elif  [ -e SPECS/${NAME}.spec ]; then
	echo SPECS/${NAME}.spec;
	exit 0;
else
	echo "No matching spec-file found"
	exit 1;
fi