#!/bin/bash

if [ -z "$1" ]; then
	echo "USAGE: $(basename $0) [OS_RELEASE]";
	exit 1;
fi

OS_RELEASE=$1

for RPM in $(find . -name "*.rpm" | grep -v src.rpm); do 
	BASE=$(basename $RPM)
	curl -X POST --data-binary @$RPM yum-01.stxt.media.int:8080/swisstxt-centos${OS_RELEASE}/$BASE
done